name: test git clone repo

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Send to slack
        id: send-to-slack
        uses: hashemallaham963/gh-actions/clone-repo@main
        with:
          repository_url: "https://github.com/hashemallaham963/gh-actions.git"
          depth: 1
          branch: "main"

      
      - name: list files and directories
        run: ls -la